from django.urls import path
from .views import (
    enviar_email,
    enviar_documentos_whatsapp_api,
    sincronizar_pasta_empresa_api,
    gerar_das_api,
    consultar_extrato_api,
    download_extrato_pdf_api,
    dashboard_summary_api,
    gerenciamento_simples_api,
    toggle_monitoramento_simples,
    gerenciamento_atribuicao_data,
    salvar_atribuicoes,
    gerar_e_enviar_das_view,
    dashboard_pie_chart,
    PendenciaAPIView,
    gerar_boleto_view,
    ultimo_resultado_sessao,
    bb_cobranca_webhook,
)

urlpatterns = [
    path('enviar-email/', enviar_email, name='enviar_email'),
    path('enviar-documentos-whatsapp/', enviar_documentos_whatsapp_api, name='enviar_documentos_whatsapp'),
    path('sincronizar-pasta/', sincronizar_pasta_empresa_api, name='sincronizar_pasta_empresa'),
    path('serpro/gerar-das/', gerar_das_api, name='gerar_das_api'),
    path('serpro/consultar-extrato/', consultar_extrato_api, name='consultar_extrato_api'),
    path('serpro/download-extrato-pdf/', download_extrato_pdf_api, name='download_extrato_pdf_api'),
    path('dashboard-summary/', dashboard_summary_api, name='dashboard_summary_api'),
    path('gerenciamento-simples/', gerenciamento_simples_api, name='gerenciamento_simples'),
    path('empresas/<int:empresa_id>/toggle-monitoramento-simples/', toggle_monitoramento_simples, name='toggle_monitoramento_simples'),
    path('gerenciamento-atribuicao-data/', gerenciamento_atribuicao_data, name='gerenciamento_atribuicao_data'),
    path('salvar-atribuicoes/', salvar_atribuicoes, name='salvar_atribuicoes'),
    path('serpro/gerar-e-enviar-das/', gerar_e_enviar_das_view, name='gerar_e_enviar_das'),
    path('pendencias/', PendenciaAPIView.as_view(), name='pendencias'),
    path('dashboard/pie-chart/', dashboard_pie_chart, name='dashboard_pie_chart'),
    path('gerar-boleto/', gerar_boleto_view, name='gerar_boleto'),
    path('ultimo-resultado-sessao/', ultimo_resultado_sessao, name='ultimo_resultado_sessao'),
    path('webhook/bb-cobranca/', bb_cobranca_webhook, name='bb_cobranca_webhook'),
]
