# Generated by Django 5.2.1 on 2025-07-11 14:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import empresas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoPessoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('nome_empresa', models.CharField(blank=True, help_text='Nome da empresa para path de upload', max_length=255, null=True)),
                ('cnpj_empresa', models.CharField(max_length=18)),
                ('tipo_documento', models.CharField(max_length=40)),
                ('caminho_arquivo', models.FileField(max_length=500, upload_to=empresas.models.departamento_pessoal_upload_path)),
                ('mes', models.CharField(max_length=2)),
                ('ano', models.CharField(max_length=4)),
                ('entregue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoEnvios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('remetente', models.CharField(max_length=20)),
                ('arquivo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha')], max_length=10)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'historico_envios',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Outros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('caminho_arquivo', models.FileField(max_length=500, upload_to=empresas.models.outros_upload_path)),
            ],
            options={
                'db_table': 'outros',
            },
        ),
        migrations.CreateModel(
            name='XML',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('nome_empresa', models.CharField(blank=True, help_text='Nome da empresa para path de upload', max_length=255, null=True)),
                ('cnpj_empresa', models.CharField(max_length=18)),
                ('tipo_documento', models.CharField(max_length=40)),
                ('caminho_arquivo', models.FileField(max_length=500, upload_to=empresas.models.xml_upload_path)),
                ('mes', models.CharField(max_length=2)),
                ('ano', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('theme', models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro')], default='light', max_length=10)),
                ('cargo', models.CharField(blank=True, choices=[('pessoal', 'Departamento Pessoal'), ('fiscal', 'Departamento Fiscal'), ('admin', 'Administrador')], default='pessoal', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosConstitutivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=40)),
                ('caminho_arquivo', models.FileField(max_length=500, upload_to=empresas.models.documentos_constitutivos_upload_path)),
            ],
            options={
                'db_table': 'empresas_documentosconstitutivos',
                'unique_together': {('nome_arquivo', 'nome_empresa', 'tipo_documento')},
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15, null=True)),
                ('simples_nacional', models.BooleanField(default=False)),
                ('inss', models.BooleanField(default=False)),
                ('fgts', models.BooleanField(default=False)),
                ('folha', models.BooleanField(default=False)),
                ('honorario', models.BooleanField(default=False)),
                ('monitorar_simples', models.BooleanField(default=True)),
                ('usuarios', models.ManyToManyField(related_name='empresas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='empresas_gerenciadas',
            field=models.ManyToManyField(blank=True, related_name='gerenciada_por', to='empresas.empresa'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INSS', 'INSS'), ('FGTS', 'FGTS'), ('Folha', 'Folha'), ('Honorário', 'Honorário'), ('Simples Nacional', 'Simples Nacional')], max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Pendência',
                'verbose_name_plural': 'Pendências',
            },
        ),
        migrations.CreateModel(
            name='SimplesNacional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('nome_empresa', models.CharField(blank=True, help_text='Nome da empresa para path de upload', max_length=255, null=True)),
                ('cnpj_empresa', models.CharField(max_length=18)),
                ('tipo_documento', models.CharField(max_length=40)),
                ('caminho_arquivo', models.FileField(max_length=500, upload_to=empresas.models.simples_nacional_upload_path)),
                ('mes', models.CharField(max_length=2)),
                ('ano', models.CharField(max_length=4)),
                ('entregue', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('nome_arquivo', 'cnpj_empresa', 'tipo_documento', 'mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='ObrigacaoMensal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('simples_nacional', 'Simples Nacional (DAS)')], max_length=50)),
                ('periodo_apuracao', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado ao Cliente'), ('nao_aplicavel', 'Não Aplicável (Sem Débito)'), ('declarado', 'Declarado'), ('consultado', 'Consultado')], default='pendente', max_length=20)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('numero_declaracao', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obrigacoes', to='empresas.empresa')),
                ('responsavel_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-periodo_apuracao', 'data_vencimento'],
                'unique_together': {('empresa', 'tipo', 'periodo_apuracao')},
            },
        ),
        migrations.CreateModel(
            name='UserCompanyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accesses', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercompanyaccess', to='empresas.empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercompanyaccess', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'empresa')},
            },
        ),
    ]
