# Generated by Django 5.2.1 on 2025-05-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='flags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
