# Generated by Django 5.2.1 on 2026-02-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='inss',
            field=models.BooleanField(default=False),
        ),
    ]
