# Generated by Django 5.2.1 on 2025-07-16 00:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_notificacao_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoenvios',
            name='data_envio',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora do envio'),
        ),
        migrations.AddField(
            model_name='historicoenvios',
            name='erro',
            field=models.TextField(blank=True, help_text='Descrição do erro, se aplicável', null=True),
        ),
        migrations.AddField(
            model_name='historicoenvios',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuário que realizou o envio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_envios', to=settings.AUTH_USER_MODEL),
        ),
    ]
