# Generated by Django 5.2.1 on 2025-05-29 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('documentos_constitutivos', 'Documentos Constitutivos'), ('departamento_pessoal', 'Departamento Pessoal'), ('xml', 'XML'), ('simples_nacional', 'Simples Nacional'), ('outros', 'Outros')], max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='empresas.pasta')),
            ],
        ),
    ]
