# Generated by Django 5.2.1 on 2025-06-12 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_funcionario_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObrigacaoMensal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('simples_nacional', 'Simples Nacional (DAS)')], max_length=50)),
                ('periodo_apuracao', models.DateField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado ao Cliente'), ('nao_aplicavel', 'Não Aplicável (Sem Débito)')], default='pendente', max_length=20)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obrigacoes', to='empresas.empresa')),
                ('responsavel_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-periodo_apuracao'],
                'unique_together': {('empresa', 'tipo', 'periodo_apuracao')},
            },
        ),
    ]
