# Generated by Django 5.2.1 on 2026-02-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_inss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='simples_nacional',
            field=models.BooleanField(default=False),
        ),
    ]
