# Generated by Django 5.2.1 on 2025-06-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_obrigacaomensal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obrigacaomensal',
            options={'ordering': ['-periodo_apuracao', 'data_vencimento']},
        ),
        migrations.AddField(
            model_name='obrigacaomensal',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
