# Generated by Django 5.2.1 on 2025-09-05 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_historicoenvios_data_envio_historicoenvios_erro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoenvios',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa relacionada ao envio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_envios', to='empresas.empresa'),
        ),
    ]
