# Generated by Django 5.2.1 on 2025-05-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_pasta_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartamentoPessoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('cnpj_empresa', models.CharField(max_length=18)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('caminho_arquivo', models.CharField(max_length=255)),
                ('mes', models.CharField(max_length=20)),
                ('ano', models.CharField(max_length=4)),
                ('entregue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='XML',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('cnpj_empresa', models.CharField(max_length=18)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('caminho_arquivo', models.CharField(max_length=255)),
                ('mes', models.CharField(max_length=20)),
                ('ano', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='pasta',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='flags',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DocumentosConstitutivos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('caminho_arquivo', models.TextField()),
            ],
            options={
                'unique_together': {('nome_arquivo', 'nome_empresa', 'tipo_documento')},
            },
        ),
        migrations.CreateModel(
            name='SimplesNacional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('cnpj_empresa', models.CharField(max_length=18)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('caminho_arquivo', models.TextField()),
                ('mes', models.CharField(max_length=20)),
                ('ano', models.CharField(max_length=4)),
                ('entregue', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('nome_arquivo', 'cnpj_empresa', 'tipo_documento', 'mes', 'ano')},
            },
        ),
        migrations.DeleteModel(
            name='Arquivo',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
    ]
