# Generated by Django 5.2.1 on 2026-02-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_simples_nacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='simples_nacional',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
