# Generated by Django 5.2.1 on 2025-06-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_alter_obrigacaomensal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='monitorar_simples',
            field=models.BooleanField(default=True),
        ),
    ]
