# Generated by Django 5.2.1 on 2025-09-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_historicoenvios_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
