# Generated by Django 5.2.1 on 2025-05-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_departamentopessoal_xml_remove_pasta_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentopessoal',
            name='caminho_arquivo',
            field=models.FileField(upload_to='departamento_pessoal/'),
        ),
        migrations.AlterField(
            model_name='documentosconstitutivos',
            name='caminho_arquivo',
            field=models.FileField(upload_to='documentos_constitutivos/'),
        ),
        migrations.AlterField(
            model_name='simplesnacional',
            name='caminho_arquivo',
            field=models.FileField(upload_to='simples_nacional/'),
        ),
        migrations.AlterField(
            model_name='xml',
            name='caminho_arquivo',
            field=models.FileField(upload_to='xml/'),
        ),
    ]
