# Generated by Django 5.2.1 on 2025-06-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_monitorar_simples'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AddField(
            model_name='funcionario',
            name='empresas_gerenciadas',
            field=models.ManyToManyField(blank=True, related_name='gerenciada_por', to='empresas.empresa'),
        ),
    ]
