# Generated by Django 5.2.1 on 2025-05-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_alter_departamentopessoal_caminho_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosconstitutivos',
            name='tipo_documento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='simplesnacional',
            name='tipo_documento',
            field=models.CharField(max_length=50),
        ),
    ]
