# Generated by Django 5.2.1 on 2026-02-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_alter_empresa_ativo_alter_empresa_desconto_taxa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ativo',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='desconto_taxa',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa de desconto (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='dia_vencimento_honorario',
            field=models.IntegerField(default=15, help_text='Dia do vencimento do boleto (1-31)', null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='dias_para_desconto',
            field=models.IntegerField(default=0, help_text='Dias até o vencimento para aplicar desconto', null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fgts',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='folha',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='honorario',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='juros_mora_taxa',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Taxa de juros mensal (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='monitorar_simples',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='multa_taxa',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Taxa de multa (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='valor_honorario',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor do honorário para geração de boleto', max_digits=10, null=True),
        ),
    ]
