# Generated by Django 5.2.1 on 2025-05-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_alter_documentosconstitutivos_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
