# Generated by Django 5.2.1 on 2025-10-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_empresa_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.CharField(blank=True, help_text='Bairro da empresa', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cep',
            field=models.CharField(blank=True, help_text='CEP sem hífen (ex.: 12345678)', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.CharField(blank=True, help_text='Cidade da empresa', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='endereco',
            field=models.CharField(blank=True, help_text='Endereço completo da empresa', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='uf',
            field=models.CharField(blank=True, help_text='UF da empresa (ex.: SP)', max_length=2, null=True),
        ),
    ]
