# Generated by Django 5.2.1 on 2026-03-08 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_alter_empresa_ativo_alter_empresa_desconto_taxa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimoResultadoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_summary', models.JSONField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ultimo_resultado_sessao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Último resultado de sessão',
                'verbose_name_plural': 'Últimos resultados de sessão',
            },
        ),
    ]
