# Generated by Django 5.2.1 on 2025-06-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_usercompanyaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrigacaomensal',
            name='numero_declaracao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='obrigacaomensal',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado ao Cliente'), ('nao_aplicavel', 'Não Aplicável (Sem Débito)'), ('declarado', 'Declarado')], default='pendente', max_length=20),
        ),
    ]
