# Generated by Django 5.2.1 on 2025-05-30 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_empresa_telefone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documentosconstitutivos',
            table='empresas_documentosconstitutivos',
        ),
    ]
