# Generated by Django 5.2.1 on 2025-12-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_empresa_bairro_empresa_cep_empresa_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='desconto_taxa',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa de desconto (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='dia_vencimento_honorario',
            field=models.IntegerField(default=15, help_text='Dia do vencimento do boleto (1-31)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='dias_para_desconto',
            field=models.IntegerField(default=0, help_text='Dias até o vencimento para aplicar desconto'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='juros_mora_taxa',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Taxa de juros mensal (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='multa_taxa',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Taxa de multa (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='empresa',
            name='valor_honorario',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor do honorário para geração de boleto', max_digits=10),
        ),
    ]
