# Generated by Django 5.2.1 on 2025-06-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_alter_documentosconstitutivos_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('caminho_arquivo', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'outros',
            },
        ),
    ]
