# Generated by Django 5.2.1 on 2026-04-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_ultimoresultadosessao'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wamid', models.CharField(max_length=255, unique=True)),
                ('to', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True)),
                ('msg_type', models.CharField(default='text', max_length=32)),
                ('timestamp', models.DateTimeField(help_text='Timestamp fornecido pela API do WhatsApp')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='whatsapp_me_timesta_230754_idx'), models.Index(fields=['to'], name='whatsapp_me_to_b911ab_idx')],
            },
        ),
    ]
