# Generated by Django 5.2.1 on 2025-06-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_obrigacaomensal_numero_declaracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrigacaomensal',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado ao Cliente'), ('nao_aplicavel', 'Não Aplicável (Sem Débito)'), ('declarado', 'Declarado'), ('consultado', 'Consultado')], default='pendente', max_length=20),
        ),
    ]
