# Generated by Django 5.2.1 on 2026-04-08 17:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_whatsappmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletoBB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_convenio', models.CharField(max_length=12)),
                ('carteira', models.CharField(blank=True, max_length=5, null=True)),
                ('variacao_carteira', models.CharField(blank=True, max_length=5, null=True)),
                ('numero_operacao', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('numero_titulo_cliente', models.CharField(max_length=30, unique=True)),
                ('nosso_numero', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('linha_digitavel', models.CharField(blank=True, max_length=80, null=True)),
                ('codigo_barra', models.CharField(blank=True, max_length=80, null=True)),
                ('valor_original', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('registrado', 'Registrado'), ('pago', 'Pago'), ('baixado', 'Baixado'), ('cancelado', 'Cancelado')], default='registrado', max_length=20)),
                ('payload_registro', models.JSONField(blank=True, default=dict)),
                ('payload_baixa', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos_bb', to='empresas.empresa')),
            ],
            options={
                'db_table': 'boletos_bb',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['numero_titulo_cliente'], name='boletos_bb_numero__5ff5c2_idx'), models.Index(fields=['nosso_numero'], name='boletos_bb_nosso_n_d6179e_idx')],
            },
        ),
    ]
