# Generated by Django 5.2.1 on 2025-06-03 17:25

import empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_outros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xml',
            name='caminho_arquivo',
            field=models.FileField(upload_to=empresas.models.xml_upload_path),
        ),
    ]
