# Generated by Django 5.2.1 on 2025-07-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_alter_obrigacaomensal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('pessoal', 'Departamento Pessoal'), ('fiscal', 'Departamento Fiscal'), ('admin', 'Administrador')], default='pessoal', max_length=100),
        ),
    ]
