# Generated by Django 5.2.1 on 2026-04-14 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_boletobb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='empresas.empresa')),
            ],
            options={
                'db_table': 'socios',
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='socio',
            constraint=models.UniqueConstraint(fields=('empresa', 'cpf'), name='unique_socio_cpf_por_empresa'),
        ),
    ]
