# Generated by Django 5.2.1 on 2025-06-03 19:39

import empresas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_alter_xml_caminho_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentopessoal',
            name='caminho_arquivo',
            field=models.FileField(max_length=500, upload_to=empresas.models.departamento_pessoal_upload_path),
        ),
        migrations.AlterField(
            model_name='departamentopessoal',
            name='mes',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='documentosconstitutivos',
            name='caminho_arquivo',
            field=models.FileField(max_length=500, upload_to=empresas.models.documentos_constitutivos_upload_path),
        ),
        migrations.AlterField(
            model_name='outros',
            name='caminho_arquivo',
            field=models.FileField(max_length=500, upload_to=empresas.models.outros_upload_path),
        ),
        migrations.AlterField(
            model_name='outros',
            name='tipo_documento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='simplesnacional',
            name='caminho_arquivo',
            field=models.FileField(max_length=500, upload_to=empresas.models.simples_nacional_upload_path),
        ),
        migrations.AlterField(
            model_name='simplesnacional',
            name='mes',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='xml',
            name='caminho_arquivo',
            field=models.FileField(max_length=500, upload_to=empresas.models.xml_upload_path),
        ),
        migrations.AlterField(
            model_name='xml',
            name='mes',
            field=models.CharField(max_length=2),
        ),
    ]
