# Generated by Django 5.2.1 on 2025-06-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_alter_departamentopessoal_caminho_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamentopessoal',
            name='tipo_documento',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='documentosconstitutivos',
            name='tipo_documento',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='simplesnacional',
            name='tipo_documento',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='xml',
            name='tipo_documento',
            field=models.CharField(max_length=40),
        ),
    ]
