# Generated by Django 5.2.1 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='numero',
            field=models.CharField(blank=True, help_text='Numero do endereco da empresa', max_length=20, null=True),
        ),
    ]
