# Generated by Django 5.2.1 on 2025-07-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_auto_20250701_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='fgts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='folha',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='honorario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='inss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='simples_nacional',
            field=models.BooleanField(default=False),
        ),
    ]
