# Generated by Django 5.2.1 on 2025-06-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_alter_departamentopessoal_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamentopessoal',
            name='nome_empresa',
            field=models.CharField(blank=True, help_text='Nome da empresa para path de upload', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simplesnacional',
            name='nome_empresa',
            field=models.CharField(blank=True, help_text='Nome da empresa para path de upload', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='xml',
            name='nome_empresa',
            field=models.CharField(blank=True, help_text='Nome da empresa para path de upload', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
