# Generated by Django 5.2.1 on 2025-06-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_departamentopessoal_nome_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEnvios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('remetente', models.CharField(max_length=20)),
                ('arquivo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha')], max_length=10)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'historico_envios',
                'ordering': ['-data_hora'],
            },
        ),
    ]
