# Generated by Django 5.2.1 on 2025-07-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_empresa_fgts_empresa_folha_empresa_honorario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
