# Generated by Django 5.2.1 on 2025-07-01 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0014_empresa_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='is_selected',
        ),
    ]
