# Generated by Django 5.2.1 on 2025-07-03 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0015_remove_empresa_is_selected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INSS', 'INSS'), ('FGTS', 'FGTS'), ('Folha', 'Folha'), ('Honorário', 'Honorário'), ('Simples Nacional', 'Simples Nacional')], max_length=50)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Pendência',
                'verbose_name_plural': 'Pendências',
            },
        ),
    ]
