# Generated by Django 5.2.1 on 2025-07-03 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0017_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usuarios',
            field=models.ManyToManyField(related_name='empresas', to=settings.AUTH_USER_MODEL),
        ),
    ]
