# Generated by Django 5.2.4 on 2026-07-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0017_honorarios_folder_structure'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boletobb',
            index=models.Index(fields=['status', 'data_vencimento'], name='boleto_status_venc_idx'),
        ),
        migrations.AddIndex(
            model_name='boletobb',
            index=models.Index(fields=['empresa', 'status'], name='boleto_empresa_status_idx'),
        ),
        migrations.AddIndex(
            model_name='boletobb',
            index=models.Index(fields=['-atualizado_em', '-criado_em'], name='boleto_atual_criado_idx'),
        ),
        migrations.AddIndex(
            model_name='departamentopessoal',
            index=models.Index(fields=['cnpj_empresa', 'ano', 'mes'], name='dp_cnpj_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='departamentopessoal',
            index=models.Index(fields=['tipo_documento', 'cnpj_empresa'], name='dp_tipo_cnpj_idx'),
        ),
        migrations.AddIndex(
            model_name='departamentopessoal',
            index=models.Index(fields=['entregue', 'cnpj_empresa'], name='dp_entregue_cnpj_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosconstitutivos',
            index=models.Index(fields=['nome_empresa'], name='doc_const_nome_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='documentosconstitutivos',
            index=models.Index(fields=['tipo_documento', 'nome_empresa'], name='doc_const_tipo_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['ativo', 'nome'], name='empresa_ativo_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['telefone'], name='empresa_telefone_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['monitorar_simples'], name='empresa_monitorar_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaavulsafaturamento',
            index=models.Index(fields=['nome'], name='emp_avulsa_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoenvios',
            index=models.Index(fields=['-data_hora'], name='hist_env_data_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoenvios',
            index=models.Index(fields=['status', '-data_hora'], name='hist_env_status_data_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoenvios',
            index=models.Index(fields=['empresa', '-data_hora'], name='hist_env_emp_data_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoenvios',
            index=models.Index(fields=['usuario', '-data_hora'], name='hist_env_user_data_idx'),
        ),
        migrations.AddIndex(
            model_name='historicoenvios',
            index=models.Index(fields=['remetente'], name='hist_env_remetente_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['destinatario', 'lida', '-timestamp'], name='notif_dest_lida_data_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['destinatario', '-timestamp'], name='notif_dest_data_idx'),
        ),
        migrations.AddIndex(
            model_name='obrigacaomensal',
            index=models.Index(fields=['status', 'data_vencimento'], name='obrig_status_venc_idx'),
        ),
        migrations.AddIndex(
            model_name='obrigacaomensal',
            index=models.Index(fields=['empresa', 'tipo', 'periodo_apuracao'], name='obrig_emp_tipo_period_idx'),
        ),
        migrations.AddIndex(
            model_name='obrigacaomensal',
            index=models.Index(fields=['tipo', 'periodo_apuracao'], name='obrig_tipo_period_idx'),
        ),
        migrations.AddIndex(
            model_name='outros',
            index=models.Index(fields=['nome_empresa', 'ano', 'mes'], name='outros_emp_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='outros',
            index=models.Index(fields=['cnpj_empresa', 'ano', 'mes'], name='outros_cnpj_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='outros',
            index=models.Index(fields=['tipo_documento', 'nome_empresa'], name='outros_tipo_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='pendencia',
            index=models.Index(fields=['empresa', 'tipo'], name='pendencia_empresa_tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='pendencia',
            index=models.Index(fields=['-data_criacao'], name='pendencia_data_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='simplesnacional',
            index=models.Index(fields=['cnpj_empresa', 'ano', 'mes'], name='sn_cnpj_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='simplesnacional',
            index=models.Index(fields=['tipo_documento', 'cnpj_empresa'], name='sn_tipo_cnpj_idx'),
        ),
        migrations.AddIndex(
            model_name='simplesnacional',
            index=models.Index(fields=['entregue', 'cnpj_empresa'], name='sn_entregue_cnpj_idx'),
        ),
        migrations.AddIndex(
            model_name='socio',
            index=models.Index(fields=['empresa', 'nome'], name='socio_empresa_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['cargo', 'nome'], name='tag_cargo_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='usercompanyaccess',
            index=models.Index(fields=['empresa', 'user'], name='usercomp_empresa_user_idx'),
        ),
        migrations.AddIndex(
            model_name='xml',
            index=models.Index(fields=['cnpj_empresa', 'ano', 'mes'], name='xml_cnpj_ano_mes_idx'),
        ),
        migrations.AddIndex(
            model_name='xml',
            index=models.Index(fields=['tipo_documento', 'cnpj_empresa'], name='xml_tipo_cnpj_idx'),
        ),
    ]
