# Generated by Django 5.2.4 on 2026-08-31 03:28

import django.db.models.deletion
import empresas.models
from django.db import migrations, models


def importar_documentos_existentes(apps, schema_editor):
    Empresa = apps.get_model('empresas', 'Empresa')
    DocumentoEmpresa = apps.get_model('empresas', 'DocumentoEmpresa')
    mappings = (
        ('DocumentosConstitutivos', 'constitutivos_outros', 'nome'),
        ('DepartamentoPessoal', 'pessoal_guias', 'cnpj'),
        ('XML', 'fiscal_xml', 'cnpj'),
        ('SimplesNacional', 'fiscal_guias', 'cnpj'),
        ('Outros', 'financeiro_honorarios_mensais', 'nome'),
    )
    empresas_nome = {empresa.nome: empresa for empresa in Empresa.objects.all()}
    empresas_cnpj = {empresa.cnpj: empresa for empresa in Empresa.objects.all()}
    for model_name, folder_key, company_field in mappings:
        Source = apps.get_model('empresas', model_name)
        for source in Source.objects.all().iterator():
            empresa = (
                empresas_nome.get(getattr(source, 'nome_empresa', None))
                if company_field == 'nome'
                else empresas_cnpj.get(getattr(source, 'cnpj_empresa', None))
            )
            if not empresa or not source.caminho_arquivo:
                continue
            DocumentoEmpresa.objects.get_or_create(
                empresa_id=empresa.pk,
                folder_key=folder_key,
                nome_arquivo=source.nome_arquivo,
                ano=getattr(source, 'ano', None) or None,
                mes=(str(getattr(source, 'mes', '') or '').zfill(2) or None),
                defaults={
                    'caminho_arquivo': source.caminho_arquivo.name,
                    'entregue': bool(getattr(source, 'entregue', False)),
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0022_normalizar_nomes_empresas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_key', models.CharField(max_length=60)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('caminho_arquivo', models.FileField(max_length=500, upload_to=empresas.models.documento_empresa_upload_path)),
                ('ano', models.CharField(blank=True, max_length=4, null=True)),
                ('mes', models.CharField(blank=True, max_length=2, null=True)),
                ('entregue', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_nova_estrutura', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-ano', '-mes', 'nome_arquivo'],
                'indexes': [models.Index(fields=['empresa', 'folder_key', 'ano', 'mes'], name='doc_empresa_pasta_periodo_idx')],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'folder_key', 'nome_arquivo', 'ano', 'mes'), name='documento_empresa_pasta_periodo_uniq', nulls_distinct=False)],
            },
        ),
        migrations.RunPython(importar_documentos_existentes, migrations.RunPython.noop),
    ]
