# Generated by Django 5.2.1 on 2026-09-21 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0025_paginasistema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('descricao', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('tarefa', 'Tarefa'), ('compromisso', 'Compromisso')], default='tarefa', max_length=20)),
                ('origem', models.CharField(default='manual', editable=False, max_length=20)),
                ('data_planejada', models.DateField(blank=True, null=True)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('termino', models.DateTimeField(blank=True, null=True)),
                ('duracao_estimada', models.PositiveIntegerField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('estado', models.CharField(choices=[('a_fazer', 'A fazer'), ('em_andamento', 'Em andamento'), ('aguardando_terceiros', 'Aguardando terceiros'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='a_fazer', max_length=30)),
                ('privada', models.BooleanField(default=False)),
                ('frequencia', models.CharField(choices=[('nenhuma', 'Não repetir'), ('diaria', 'Diária'), ('dias_uteis', 'Dias úteis'), ('semanal', 'Semanal'), ('mensal', 'Mensal')], default='nenhuma', max_length=20)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_criadas', to=settings.AUTH_USER_MODEL)),
                ('compartilhados', models.ManyToManyField(blank=True, related_name='atividades_compartilhadas', to=settings.AUTH_USER_MODEL)),
                ('concluida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_concluidas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='empresas.empresa')),
                ('recorrencia_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='empresas.atividade')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_planejada', 'inicio', '-prioridade', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BlocoExecucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('termino', models.DateTimeField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='empresas.atividade')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos_execucao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['inicio', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['responsavel', 'data_planejada'], name='ativ_resp_data_idx'),
        ),
        migrations.AddIndex(
            model_name='atividade',
            index=models.Index(fields=['estado', 'prazo'], name='ativ_estado_prazo_idx'),
        ),
        migrations.AddConstraint(
            model_name='atividade',
            constraint=models.UniqueConstraint(fields=('recorrencia_origem', 'data_planejada'), name='atividade_recorrencia_data_uniq'),
        ),
    ]
