"""
Django settings for sistema_inovar project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nyztzhaza2*5^7eq30-^c2juo3c*btz5v899x6pv@o76gac2a+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['*']

CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'empresas',
    'corsheaders',
    
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # (Opcional) Você pode definir permissões padrão aqui também
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ]
}

ROOT_URLCONF = 'sistema_inovar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_inovar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sistemaweb2',
        'USER': 'postgres',
        'PASSWORD': '@hoanD1323',
        'HOST': '192.168.196.162',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://192.168.196.162:3000",
    "http://localhost:3000", 
]

MEDIA_URL = '/media/'
MEDIA_ROOT = r'\\servidor\SERVIDOR INOVAR\SISTEMA INOVAR TESTE (NAO MEXER)'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Usar decouple com fallback
try:
    from decouple import config
    print("Decouple importado com sucesso")
    EMAIL_REMETENTE = config('EMAIL_REMETENTE', default='default_email@example.com')
    EMAIL_SENHA_APP = config('EMAIL_SENHA_APP', default='default_senha')
except ImportError as e:
    print(f"Erro ao importar decouple: {e}")
    EMAIL_REMETENTE = 'default_email@example.com'
    EMAIL_SENHA_APP = 'default_senha'


WHATSAPP_ACCESS_TOKEN = 'EAANIXCvVAZBwBO59BDRjh5i1VivZAZB1ZA2n14ZBuh1gV4pZBZBZBnoJHzhoT7dPWNUGO5wuSqevJDwvqSn9xkfZAF87QK2rN2YMNRQNiKNGkGZBfSQTpnvuwvTEZBxlH17YkFtkZA7MrWh7zZA0ZCpnjIn3UEOEuPhiQs484T3x3Jf5Vbj7oLD5V3lC5OACZAYhUVCqQZDZD'
WHATSAPP_PHONE_NUMBER_ID = '638831082650518'
WHATSAPP_API_VERSION = 'v20.0' 
WHATSAPP_TEMPLATE_NAME_DOCS = 'envio_documento_com_contato'


AUTH_USER_MODEL = 'empresas.Funcionario'

# Credenciais do Serpro lidas de variáveis de ambiente
SERPRO_CONSUMER_KEY = os.environ.get('q4zLdPcssela_ZQK0eUEKxHqxRQa')
SERPRO_CONSUMER_SECRET = os.environ.get('Pb39qTxZZorWU_LZOfeEjEtN4uUa')

# Caminho para o certificado e a senha (lida do ambiente)
SERPRO_CERT_PATH = r'\\servidor\SERVIDOR INOVAR\CERTIFICADO\FABIO LUIS DE FREITAS.pfx'
SERPRO_CERT_PASSWORD = os.environ.get('123456')