"""
Django settings for sistema_inovar project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nyztzhaza2*5^7eq30-^c2juo3c*btz5v899x6pv@o76gac2a+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ['*']

CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'empresas',
    'corsheaders',
    'django_filters'
    
]

MIDDLEWARE = [
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]


ROOT_URLCONF = 'sistema_inovar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_inovar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sistema_inovar_web',
        'USER': 'postgres',
        'PASSWORD': '@hoanD1323',
        'HOST': '192.168.196.162',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}
from datetime import timedelta

# SimpleJWT Configuration (deve vir após REST_FRAMEWORK)
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),  # Mantém o padrão de 5 minutos
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),   # Aumenta para 7 dias
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://192.168.196.162:3000",
    "http://localhost:3000", 
]

MEDIA_URL = '/media/'
MEDIA_ROOT = r'\\servidor\SERVIDOR INOVAR\SISTEMA INOVAR'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Usar decouple com fallback
try:
    from decouple import config
    print("Decouple importado com sucesso")
    EMAIL_REMETENTE = config('EMAIL_REMETENTE', default='default_email@example.com')
    EMAIL_SENHA_APP = config('EMAIL_SENHA_APP', default='default_senha')

    SERPRO_CONSUMER_KEY = config('SERPRO_CONSUMER_KEY')
    SERPRO_CONSUMER_SECRET = config('SERPRO_CONSUMER_SECRET')
    SERPRO_CERT_PASSWORD = config('SERPRO_CERT_PASSWORD')

    SERPRO_TOKEN_URL = 'https://gateway.apiserpro.serpro.gov.br/integra-contador/v1/token'
    SERPRO_API_URL = 'https://gateway.apiserpro.serpro.gov.br/integra-contador-trial/v1/Consultar'

    MEU_ESCRITORIO_CNPJ = config('MEU_ESCRITORIO_CNPJ')
except ImportError as e:
    print(f"Erro ao importar decouple: {e}")
    EMAIL_REMETENTE = 'default_email@example.com'
    EMAIL_SENHA_APP = 'default_senha'

    SERPRO_CONSUMER_KEY = ''
    SERPRO_CONSUMER_SECRET = ''
    SERPRO_CERT_PASSWORD = ''
    MEU_ESCRITORIO_CNPJ = ''


WHATSAPP_ACCESS_TOKEN = 'EAANIXCvVAZBwBO59BDRjh5i1VivZAZB1ZA2n14ZBuh1gV4pZBZBZBnoJHzhoT7dPWNUGO5wuSqevJDwvqSn9xkfZAF87QK2rN2YMNRQNiKNGkGZBfSQTpnvuwvTEZBxlH17YkFtkZA7MrWh7zZA0ZCpnjIn3UEOEuPhiQs484T3x3Jf5Vbj7oLD5V3lC5OACZAYhUVCqQZDZD'
WHATSAPP_PHONE_NUMBER_ID = '638831082650518'
WHATSAPP_API_VERSION = 'v20.0' 
WHATSAPP_TEMPLATE_NAME_DOCS = 'envio_documento_com_contato'


AUTH_USER_MODEL = 'empresas.Funcionario'

SERPRO_CERT_PUBLIC_PATH = r'\\servidor\SERVIDOR INOVAR\CERTIFICADO\certificado_publico.pem'
SERPRO_CERT_PRIVATE_KEY_PATH = r'\\servidor\SERVIDOR INOVAR\CERTIFICADO\chave_privada_sem_senha.pem'

# Configurações do Banco do Brasil (Sandbox)
BB_API_BASE_URL = 'https://api.bb.com.br/cobrancas/v2'
BB_OAUTH_URL = 'https://oauth.bb.com.br/oauth/token'
BB_CLIENT_ID = 'eyJpZCI6IjVhY2ZlY2YtNDgzMS00MzczLTllIiwiY29kaWdvUHVibGljYWRvciI6MCwiY29kaWdvU29mdHdhcmUiOjE0MTQ1NCwic2VxdWVuY2lhbEluc3RhbGFjYW8iOjF9' 
BB_CLIENT_SECRET = 'eyJpZCI6ImRlZCIsImNvZGlnb1B1YmxpY2Fkb3IiOjAsImNvZGlnb1NvZnR3YXJlIjoxNDE0NTQsInNlcXVlbmNpYWxJbnN0YWxhY2FvIjoxLCJzZXF1ZW5jaWFsQ3JlZGVuY2lhbCI6MSwiYW1iaWVudGUiOiJwcm9kdWNhbyIsImlhdCI6MTc2Njc2NzE3NzE2MH0'
BB_DEVELOPER_APPLICATION_KEY = '935eae651fe6473fb8627af35c5acb26'
BB_SCOPE = ''
BB_BANK_CODE_WITH_DV = "001-9"
